name: STGroup-dxw
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - matplotlib=3.10.0
  - pip
  - pip:
      - torch==2.2.0+cu121
      - torchvision==0.17.0+cu121
      - torchaudio==2.2.0+cu121
      - --extra-index-url https://download.pytorch.org/whl/cu121
